### PR TITLE
dark theme

### PR DESCRIPTION
**Pull request by CharleneMills**
Dark theme added to readme template

### CODE REVIEW

**Review by inetknght — CHANGES_REQUESTED** [review]
Dark looks good. More font colors needs to be updated though.

Screenshot_20200731_183629

**Comment by CharleneMills** [comment]
Oh hahaha! Sorry. Just the black to white. Do you want the purple visited slightly lighter?

Thanks,
Charlene

**Comment by CharleneMills** [comment]
Paragraph color white has been added. Did you want the purple visited link color to be lighter?

**Comment by inetknght** [comment]
Re purple: sure. There's still some text whose color is too dark to be adjusted though. Consider:

* `Basic service file documentation` under `www/index.html`
* `sshfs` options under `www/examples/index.html`
* bullet points under `www/examples/index.html`

Screenshot_20200801_143854
Screenshot_20200801_144040

**Comment by CharleneMills** [comment]
I cant view what im doing because i dont have the same build as you. So its all guess work.

Thanks,
Charlene

**Comment by inetknght** [comment]
You can. Install Python 3 then,

`python3 -m pip install -r ./requirements.txt` to install package dependencies

Then you can do `python3 ./build.py` to build the site.

**Comment by CharleneMills** [comment]
okay just add 
ul li, ol li { color: white; }

**Comment by inetknght** [comment]
:+1: I figured out how to get that working. I added it to the body instead since `color:white` was being said often

**Comment by CharleneMills** [comment]
That works too! Youre a CSS master now! 😄

Thanks,
Charlene

**Pull request merged**
